### ISSUE TITLE
Collection hétérogène de Stockage : Tableau des pointeurs de PWM, PPM, FASTA

### ISSUE THREAD

**Issue by richiefuwafuwa** [EPFL-SV-cpp-projects/genom-6#10]
Créér cette collection (liste des fichiers stockés) qqpart, soit dans Reader (???) besoin d'en discuter demain pour savoir où le mettre.

**Comment by julian-barry** [comment]
Issue resolved : We decided to have an abstract super class Data with subclasses MAT and FASTA. Reader shall provide data from files to these classes.
